/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplicacion;

import Libreria.*;

/**
 *
 * @author bellavista
 */
public class FormVenta extends javax.swing.JFrame {

    /**
     * Creates new form FormVenta
     */
    public FormVenta() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf_id_venta = new javax.swing.JTextField();
        tf_cantidad = new javax.swing.JTextField();
        tf_precioUnitario = new javax.swing.JTextField();
        b_cuota = new javax.swing.JButton();
        b_restablecer = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        tf_venta = new javax.swing.JTextField();
        tf_mensaje = new javax.swing.JTextField();
        b_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Monto de Venta");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cantidad");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Numero");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Precio Unitario");

        tf_id_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_id_venta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tf_cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_cantidad.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tf_precioUnitario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_precioUnitario.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        b_cuota.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_cuota.setText("Consultar");
        b_cuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cuotaActionPerformed(evt);
            }
        });

        b_restablecer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_restablecer.setText("Restablecer");
        b_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_restablecerActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Monto Ventas");

        tf_venta.setEditable(false);
        tf_venta.setBackground(new java.awt.Color(255, 255, 255));
        tf_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_venta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        tf_mensaje.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_mensaje.setForeground(new java.awt.Color(255, 0, 0));
        tf_mensaje.setText("Zona de Mensajes");

        b_salir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        b_salir.setText("Salir");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tf_id_venta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                        .addComponent(tf_cantidad, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b_cuota)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_restablecer)))
                        .addGap(28, 28, 28)
                        .addComponent(b_salir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_venta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tf_mensaje))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_id_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_precioUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b_cuota)
                        .addComponent(b_restablecer)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_restablecerActionPerformed
        // TODO add your handling code here:
        tf_id_venta.setText("");
        tf_cantidad.setText("");
        tf_precioUnitario.setText("");
        tf_venta.setText("");
        tf_mensaje.setText("");
        tf_id_venta.requestFocus();
    }//GEN-LAST:event_b_restablecerActionPerformed

    private void b_cuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cuotaActionPerformed
        // TODO add your handling code here:
        TryParse tp = new TryParse();
        if(tp.esInteger(tf_id_venta.getText())){
            int id_venta = Integer.valueOf(tf_id_venta.getText());
            if(id_venta > 0){
                if(tp.esInteger(tf_cantidad.getText())) {
                    int cantidad = Integer.valueOf(tf_cantidad.getText());
                    if(cantidad> 0) {
                        if(tp.esFloat(tf_precioUnitario.getText())) {
                            int precioUnitario = Integer.valueOf(tf_precioUnitario.getText());
                            if(precioUnitario>0) {
                                Venta a = new Venta();
                                a.setId_venta(id_venta);
                                a.setCantidad(cantidad);
                                a.setPrecioUnitario(precioUnitario);
                                int venta = a.obtenerMontoVenta();
                                tf_venta.setText(String.valueOf(venta));
                            } else {
                                tf_mensaje.setText("Debe ingresar el Precio Unitario > 0");
                                tf_precioUnitario.requestFocus();                                  
                            }
                        } else {
                            tf_mensaje.setText("Debe ingresar un Precio Unitario valido");
                            tf_precioUnitario.requestFocus();                             
                        }
                    } else {
                        tf_mensaje.setText("Debe ingresar un número de Cantidad > 0");
                        tf_cantidad.requestFocus();                         
                    }
                } else {
                    tf_mensaje.setText("Debe ingresar un número de Cantidad valido");
                    tf_cantidad.requestFocus();                    
                }
            }else {
                tf_mensaje.setText("Debe ingresar un ID de Venta > 0");
                tf_id_venta.requestFocus();                
            }
        } else {
            tf_mensaje.setText("Debe ingresar un ID de Venta valido");
            tf_id_venta.requestFocus();
        }
    }//GEN-LAST:event_b_cuotaActionPerformed

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        // TODO add your handling code here:

       System.exit(0);
    
    }//GEN-LAST:event_b_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cuota;
    private javax.swing.JButton b_restablecer;
    private javax.swing.JButton b_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField tf_cantidad;
    private javax.swing.JTextField tf_id_venta;
    private javax.swing.JTextField tf_mensaje;
    private javax.swing.JTextField tf_precioUnitario;
    private javax.swing.JTextField tf_venta;
    // End of variables declaration//GEN-END:variables
}
